# Generated by Django 4.2.7 on 2023-12-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammar',
            name='additional1',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='grammar',
            name='additional2',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='grammar',
            name='additional3',
            field=models.CharField(blank=True, default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='grammar',
            name='additional4',
            field=models.CharField(blank=True, default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='grammar',
            name='example3',
            field=models.CharField(blank=True, default=None, max_length=400),
        ),
        migrations.AddField(
            model_name='grammar',
            name='example4',
            field=models.CharField(blank=True, default=None, max_length=400),
        ),
    ]
