# Generated by Django 4.2.7 on 2023-12-20 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0002_grammar_additional1_grammar_additional2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grammar',
            name='additional1',
        ),
        migrations.RemoveField(
            model_name='grammar',
            name='additional2',
        ),
        migrations.RemoveField(
            model_name='grammar',
            name='additional3',
        ),
        migrations.RemoveField(
            model_name='grammar',
            name='additional4',
        ),
        migrations.RemoveField(
            model_name='grammar',
            name='example1',
        ),
        migrations.RemoveField(
            model_name='grammar',
            name='example2',
        ),
        migrations.RemoveField(
            model_name='grammar',
            name='example3',
        ),
        migrations.RemoveField(
            model_name='grammar',
            name='example4',
        ),
    ]
